extern const volatile unsigned int __kernel_end;
#define disk_start 0x7c00
#define vfs_start ((unsigned long) &__kernel_end) + 80
#include "stdint.hpp"
#include "stdbool.hpp"
#include "fixlinker.cpp"
#include "ports.cpp"
#include "express.cpp"
#include "taskmanager.cpp"
#include "icfs.hpp"
#include "qq.hpp"
#include "utility.cpp"
#include "frenzyui.cpp"
#include "isct.hpp"
#include "rclass.cpp"
#include "time.cpp"
#include "sound.cpp"
#include "graphics.cpp"
#include "font.cpp"
#include "input.cpp"
#include "graphics_elements.cpp"
#include "commandManager.cpp"
#include "memory.cpp"
#include "task.cpp"
#include "main.cpp"